In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)

RAW_DATA_PATH = Path("../data/raw")

In [35]:
orders = pd.read_csv(
    RAW_DATA_PATH / "olist_orders_dataset.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
)

order_items = pd.read_csv(
    RAW_DATA_PATH / "olist_order_items_dataset.csv",
    parse_dates=["shipping_limit_date"],
)

customers = pd.read_csv(
    RAW_DATA_PATH / "olist_customers_dataset.csv"
)

products = pd.read_csv(
    RAW_DATA_PATH / "olist_products_dataset.csv"
)

sellers = pd.read_csv(
    RAW_DATA_PATH / "olist_sellers_dataset.csv"
)

payments = pd.read_csv(
    RAW_DATA_PATH / "olist_order_payments_dataset.csv"
)

In [36]:
tables = {
    "orders": orders,
    "order_items": order_items,
    "customers": customers,
    "products": products,
    "sellers": sellers,
    "payments": payments,
}

In [5]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [133]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
]
delivered_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [117]:
print(delivered_orders["order_delivered_customer_date"].isnull().sum())

8

In [118]:
print(delivered_orders["order_estimated_delivery_date"].isnull().sum() )

0

In [134]:
delivered_orders.dropna(
    subset=["order_delivered_customer_date"],
    inplace=True
)

In [135]:
delivered_orders["late_delivery"] = (
    delivered_orders["order_delivered_customer_date"] > delivered_orders["order_estimated_delivery_date"]
).astype(int)

In [121]:
delivered_orders["late_delivery"].value_counts()

late_delivery
0    88644
1     7826
Name: count, dtype: int64

In [136]:
delivered_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0

In [123]:
delivered_orders["order_id"].nunique()

96470

In [124]:
delivered_orders["order_id"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_id, Length: 96470, dtype: bool

In [47]:
order_items.shape

(112650, 7)

In [48]:
products.shape

(32951, 9)

In [49]:
sellers.shape

(3095, 4)

In [50]:
payments.shape

(103886, 5)

In [60]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [59]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [61]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [62]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [63]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [65]:
for table in tables.values():
    print(table.duplicated().sum())

0
0
0
0
0
0

In [66]:
for table in tables.values():
    print(table.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [67]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [68]:
customers[customers["customer_id"].duplicated(keep=False)]

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

In [71]:
order_items["order_item_id"].duplicated().sum()

np.int64(112629)

In [72]:
orders[~orders["customer_id"].isin(customers["customer_id"])]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [75]:
# Every order customer exists in customers
print((~orders["customer_id"].isin(customers["customer_id"])).sum())

# Every item order exists in orders
print((~order_items["order_id"].isin(orders["order_id"])).sum())

# Every item product exists in products
print((~order_items["product_id"].isin(products["product_id"])).sum())

# Every item seller exists in sellers
print((~order_items["seller_id"].isin(sellers["seller_id"])).sum())

# Every payment order exists in orders
print((~payments["order_id"].isin(orders["order_id"])).sum())

0
0
0
0
0

In [76]:
items_enriched=order_items.merge(
    products,
    on="product_id",
    how="left",
    validate="m:1",
    indicator="_product_match"

)

In [77]:
items_enriched["_product_match"].value_counts()

_product_match
both          112650
left_only          0
right_only         0
Name: count, dtype: int64

In [78]:
items_enriched.isna().sum().sort_values(ascending=False)

product_category_name         1603
product_photos_qty            1603
product_description_lenght    1603
product_name_lenght           1603
product_weight_g                18
product_width_cm                18
product_height_cm               18
product_length_cm               18
freight_value                    0
price                            0
shipping_limit_date              0
seller_id                        0
order_item_id                    0
product_id                       0
order_id                         0
_product_match                   0
dtype: int64

In [79]:
items_enriched = items_enriched.drop(columns="_product_match")

In [91]:
items_enriched = items_enriched.merge(
    sellers,
    on="seller_id",
    how="left",
    validate="m:1",
    indicator="_seller_match"
)

ValueError: Cannot use name of an existing column for indicator column

In [81]:
items_enriched["_seller_match"].value_counts()

_seller_match
both          112650
left_only          0
right_only         0
Name: count, dtype: int64

In [92]:
items_enriched = items_enriched.drop(columns="_seller_match")

In [93]:
print(items_enriched.shape)
print(items_enriched["order_id"].nunique())

(112650, 21)
98666

In [85]:
order_item_summary = (
    items_enriched
    .groupby("order_id", as_index=False)
    .agg(
        number_of_items=("order_item_id", "count"),
        number_of_unique_products=("product_id", "nunique"),
        number_of_unique_sellers=("seller_id", "nunique"),
        total_product_price=("price", "sum"),
        total_freight_value=("freight_value", "sum"),
        average_product_weight_g=("product_weight_g", "mean"),
        average_product_length_cm=("product_length_cm", "mean"),
        average_product_height_cm=("product_height_cm", "mean"),
        average_product_width_cm=("product_width_cm", "mean"),
        number_of_product_categories=("product_category_name", "nunique")
    )
)

In [125]:
order_item_summary

,order_id,number_of_items,number_of_unique_products,number_of_unique_sellers,total_product_price,total_freight_value,average_product_weight_g,average_product_length_cm,average_product_height_cm,average_product_width_cm,number_of_product_categories
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29,650.0,28.0,9.0,14.0,1
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93,30000.0,50.0,30.0,40.0,1
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87,3050.0,33.0,13.0,33.0,1
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79,200.0,16.0,10.0,15.0,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14,3750.0,35.0,40.0,30.0,1
...,...,...,...,...,...,...,...,...,...,...,...
98661,fffc94f6ce00a00581880bf54a75a037,1,1,1,299.99,43.41,10150.0,89.0,15.0,40.0,1
98662,fffcd46ef2263f404302a634eb57f7eb,1,1,1,350.00,36.53,8950.0,45.0,26.0,38.0,1
98663,fffce4705a9662cd70adb13d4a31832d,1,1,1,99.90,16.95,967.0,21.0,24.0,19.0,1
98664,fffe18544ffabc95dfada21779c9644f,1,1,1,55.99,8.72,100.0,20.0,20.0,20.0,1
98665,fffe41c64501cc87c801fd61db3f6244,1,1,1,43.00,12.79,600.0,30.0,3.0,19.0,1

In [88]:
order_item_summary["order_id"].duplicated().sum()

np.int64(0)

In [95]:
payments.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [97]:
order_level_payments = (
    payments.groupby("order_id", as_index=False)
    .agg(
        total_payment_installments=("payment_installments", "sum"),
        total_payment_value=("payment_value", "sum"),
        number_of_payment_records=("payment_sequential", "count")
    )
)
order_level_payments

,order_id,total_payment_installments,total_payment_value,number_of_payment_records
0,00010242fe8c5a6d1ba2dd792cb16214,2,72.19,1
1,00018f77f2f0320c557190d7a144bdd3,3,259.83,1
2,000229ec398224ef6ca0657da4fc703e,5,216.87,1
3,00024acbcdf0a6daa1e931b038114c75,2,25.78,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,3,218.04,1
...,...,...,...,...
99435,fffc94f6ce00a00581880bf54a75a037,1,343.40,1
99436,fffcd46ef2263f404302a634eb57f7eb,1,386.53,1
99437,fffce4705a9662cd70adb13d4a31832d,3,116.85,1
99438,fffe18544ffabc95dfada21779c9644f,3,64.71,1
99439,fffe41c64501cc87c801fd61db3f6244,1,55.79,1

In [98]:
primary_payment_type = (
    payments
    .sort_values(
        ["order_id", "payment_value", "payment_sequential"],
        ascending=[True, False, True]
    )
    .drop_duplicates(subset="order_id", keep="first")
    [["order_id", "payment_type"]]
    .rename(columns={"payment_type": "primary_payment_type"})
)

In [100]:
order_level_payments = order_level_payments.merge(
    primary_payment_type,
    on="order_id",
    how="left",
    validate="one_to_one"
)
order_level_payments

,order_id,total_payment_installments,total_payment_value,number_of_payment_records,primary_payment_type_x,primary_payment_type_y
0,00010242fe8c5a6d1ba2dd792cb16214,2,72.19,1,credit_card,credit_card
1,00018f77f2f0320c557190d7a144bdd3,3,259.83,1,credit_card,credit_card
2,000229ec398224ef6ca0657da4fc703e,5,216.87,1,credit_card,credit_card
3,00024acbcdf0a6daa1e931b038114c75,2,25.78,1,credit_card,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,3,218.04,1,credit_card,credit_card
...,...,...,...,...,...,...
99435,fffc94f6ce00a00581880bf54a75a037,1,343.40,1,boleto,boleto
99436,fffcd46ef2263f404302a634eb57f7eb,1,386.53,1,boleto,boleto
99437,fffce4705a9662cd70adb13d4a31832d,3,116.85,1,credit_card,credit_card
99438,fffe18544ffabc95dfada21779c9644f,3,64.71,1,credit_card,credit_card
99439,fffe41c64501cc87c801fd61db3f6244,1,55.79,1,credit_card,credit_card

In [ ]:
order_level_payments["order_id"].nunique()

99440

In [126]:
delivered_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0

In [137]:
delivered_orders_summary = delivered_orders.merge(
    customers,
    on="customer_id",
    how="left",
    validate="many_to_one"
)
delivered_orders_summary

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96465,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP
96466,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP
96467,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA
96468,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
96469,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR

In [128]:
order_item_summary

,order_id,number_of_items,number_of_unique_products,number_of_unique_sellers,total_product_price,total_freight_value,average_product_weight_g,average_product_length_cm,average_product_height_cm,average_product_width_cm,number_of_product_categories
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29,650.0,28.0,9.0,14.0,1
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93,30000.0,50.0,30.0,40.0,1
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87,3050.0,33.0,13.0,33.0,1
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79,200.0,16.0,10.0,15.0,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14,3750.0,35.0,40.0,30.0,1
...,...,...,...,...,...,...,...,...,...,...,...
98661,fffc94f6ce00a00581880bf54a75a037,1,1,1,299.99,43.41,10150.0,89.0,15.0,40.0,1
98662,fffcd46ef2263f404302a634eb57f7eb,1,1,1,350.00,36.53,8950.0,45.0,26.0,38.0,1
98663,fffce4705a9662cd70adb13d4a31832d,1,1,1,99.90,16.95,967.0,21.0,24.0,19.0,1
98664,fffe18544ffabc95dfada21779c9644f,1,1,1,55.99,8.72,100.0,20.0,20.0,20.0,1
98665,fffe41c64501cc87c801fd61db3f6244,1,1,1,43.00,12.79,600.0,30.0,3.0,19.0,1

In [138]:
delivered_orders_summary = delivered_orders_summary.merge(
    order_item_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)
delivered_orders_summary

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,number_of_items,number_of_unique_products,number_of_unique_sellers,total_product_price,total_freight_value,average_product_weight_g,average_product_length_cm,average_product_height_cm,average_product_width_cm,number_of_product_categories
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,1,1,29.99,8.72,500.0,19.0,8.0,13.0,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,1,1,118.70,22.76,400.0,19.0,13.0,19.0,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,1,1,159.90,19.22,420.0,24.0,19.0,21.0,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,1,1,45.00,27.20,450.0,30.0,10.0,20.0,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,1,1,19.90,8.72,250.0,51.0,15.0,15.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96465,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,1,1,1,72.00,13.08,1175.0,22.0,13.0,18.0,1
96466,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,1,1,1,174.90,20.10,4950.0,40.0,10.0,40.0,1
96467,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,1,1,1,205.99,65.02,13300.0,32.0,90.0,22.0,1
96468,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,2,1,1,359.98,81.18,6550.0,20.0,20.0,20.0,1
96469,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,1,1,1,68.50,18.36,150.0,16.0,7.0,15.0,1

In [139]:
delivered_orders_summary = delivered_orders_summary.merge(
    order_level_payments,
    on="order_id",
    how="left",
    validate="one_to_one"
)

In [140]:
delivered_orders_summary

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,number_of_items,number_of_unique_products,number_of_unique_sellers,total_product_price,total_freight_value,average_product_weight_g,average_product_length_cm,average_product_height_cm,average_product_width_cm,number_of_product_categories,total_payment_installments,total_payment_value,number_of_payment_records,primary_payment_type_x,primary_payment_type_y
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,1,1,29.99,8.72,500.0,19.0,8.0,13.0,1,3.0,38.71,3.0,voucher,voucher
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,1,1,118.70,22.76,400.0,19.0,13.0,19.0,1,1.0,141.46,1.0,boleto,boleto
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,1,1,159.90,19.22,420.0,24.0,19.0,21.0,1,3.0,179.12,1.0,credit_card,credit_card
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,1,1,45.00,27.20,450.0,30.0,10.0,20.0,1,1.0,72.20,1.0,credit_card,credit_card
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,1,1,19.90,8.72,250.0,51.0,15.0,15.0,1,1.0,28.62,1.0,credit_card,credit_card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96465,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,1,1,1,72.00,13.08,1175.0,22.0,13.0,18.0,1,3.0,85.08,1.0,credit_card,credit_card
96466,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,1,1,1,174.90,20.10,4950.0,40.0,10.0,40.0,1,3.0,195.00,1.0,credit_card,credit_card
96467,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,1,1,1,205.99,65.02,13300.0,32.0,90.0,22.0,1,5.0,271.01,1.0,credit_card,credit_card
96468,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,2,1,1,359.98,81.18,6550.0,20.0,20.0,20.0,1,4.0,441.16,1.0,credit_card,credit_card
96469,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,1,1,1,68.50,18.36,150.0,16.0,7.0,15.0,1,1.0,86.86,1.0,debit_card,debit_card

In [141]:
delivered_orders_summary["order_id"].duplicated().sum()

np.int64(0)

In [142]:
delivered_orders_summary.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      1
order_delivered_customer_date     0
order_estimated_delivery_date     0
late_delivery                     0
customer_unique_id                0
customer_zip_code_prefix          0
customer_city                     0
customer_state                    0
number_of_items                   0
number_of_unique_products         0
number_of_unique_sellers          0
total_product_price               0
total_freight_value               0
average_product_weight_g         16
average_product_length_cm        16
average_product_height_cm        16
average_product_width_cm         16
number_of_product_categories      0
total_payment_installments        1
total_payment_value               1
number_of_payment_records         1
primary_payment_type_x            1
primary_payment_type_y            1
dtype: int64

In [146]:
delivered_orders_summary.dropna(subset="order_approved_at", inplace=True)

In [159]:
delivered_orders_summary.shape

(96456, 24)

In [ ]:
delivered_orders_summary = delivered_orders_summary.drop(
    columns=[
        "order_status",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
)

KeyError: "['order_status', 'order_delivered_carrier_date', 'order_delivered_customer_date'] not found in axis"

In [157]:
delivered_orders_summary.columns.tolist()

['order_id',
 'customer_id',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_estimated_delivery_date',
 'late_delivery',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'number_of_items',
 'number_of_unique_products',
 'number_of_unique_sellers',
 'total_product_price',
 'total_freight_value',
 'average_product_weight_g',
 'average_product_length_cm',
 'average_product_height_cm',
 'average_product_width_cm',
 'number_of_product_categories',
 'total_payment_installments',
 'total_payment_value',
 'number_of_payment_records',
 'primary_payment_type']

In [158]:
missing_report = pd.DataFrame({
    "null_count": delivered_orders_summary.isna().sum(),
    "null_percentage": (
        delivered_orders_summary.isna().mean() * 100
    ).round(4)
})

missing_report = (
    missing_report[missing_report["null_count"] > 0]
    .sort_values("null_percentage", ascending=False)
)

missing_report

                            null_count  null_percentage
average_product_weight_g            16           0.0166
average_product_length_cm           16           0.0166
average_product_height_cm           16           0.0166
average_product_width_cm            16           0.0166
total_payment_installments           1           0.0010
total_payment_value                  1           0.0010
number_of_payment_records            1           0.0010
primary_payment_type                 1           0.0010

In [160]:
output_path = "../data/processed/order_level_dataset.csv"

delivered_orders_summary.to_csv(
    output_path,
    index=False
)

In [161]:
order_level_dataset = delivered_orders_summary.copy()

del delivered_orders_summary

In [162]:
order_level_dataset

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,number_of_items,number_of_unique_products,number_of_unique_sellers,total_product_price,total_freight_value,average_product_weight_g,average_product_length_cm,average_product_height_cm,average_product_width_cm,number_of_product_categories,total_payment_installments,total_payment_value,number_of_payment_records,primary_payment_type
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,1,1,29.99,8.72,500.0,19.0,8.0,13.0,1,3.0,38.71,3.0,voucher
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,1,1,118.70,22.76,400.0,19.0,13.0,19.0,1,1.0,141.46,1.0,boleto
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,1,1,159.90,19.22,420.0,24.0,19.0,21.0,1,3.0,179.12,1.0,credit_card
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,1,1,45.00,27.20,450.0,30.0,10.0,20.0,1,1.0,72.20,1.0,credit_card
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,1,1,19.90,8.72,250.0,51.0,15.0,15.0,1,1.0,28.62,1.0,credit_card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96465,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-28,0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,1,1,1,72.00,13.08,1175.0,22.0,13.0,18.0,1,3.0,85.08,1.0,credit_card
96466,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-03-02,0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,1,1,1,174.90,20.10,4950.0,40.0,10.0,40.0,1,3.0,195.00,1.0,credit_card
96467,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-09-27,0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,1,1,1,205.99,65.02,13300.0,32.0,90.0,22.0,1,5.0,271.01,1.0,credit_card
96468,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-02-15,0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,2,1,1,359.98,81.18,6550.0,20.0,20.0,20.0,1,4.0,441.16,1.0,credit_card
96469,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-04-03,0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,1,1,1,68.50,18.36,150.0,16.0,7.0,15.0,1,1.0,86.86,1.0,debit_card